export const testimonials = [
	{
		id: 1,
		name: 'Adeeba C.',
		initials: 'AC',
		rating: 5.0,
		date: 'Mar 8, 2024',
		project: 'Convert figma design into Next.js TypeScript',
		testimonial:
			"Great worker who does a fantastic job. I'd highly recommend him for any future products and would collab again",
		highlight: 'Figma to Next.js conversion expertise',
		role: 'Frontend Developer',
	},
	// {
	// 	id: 6,
	// 	name: 'Cofounderslab A.',
	// 	initials: 'CA',
	// 	rating: 5.0,
	// 	date: 'Apr 26, 2023',
	// 	project: 'React Junior $3p/h',
	// 	testimonial: '', // Not fully visible in image
	// 	highlight: 'React development',
	// 	role: 'Software Developer',
	// },
	{
		id: 2,
		name: 'Kareem D.',
		initials: 'KD',
		rating: 5.0,
		date: 'Nov 28, 2023',
		project: 'Help building frontend of a lawn mowing React app',
		testimonial:
			'Great developer. If you need quick clean code Brian is an excellent choice. If I ever need work done he will be my first choice.',
		highlight: 'Quick, clean code delivery',
		role: 'Software Developer',
	},
	{
		id: 3,
		name: 'Abhinav M.',
		initials: 'AM',
		rating: 5.0,
		date: 'Oct 13, 2023',
		project: 'Build Admin Panel for Tracking',
		testimonial:
			'Great work quality and strong collaboration as always. Highly recommended!',
		highlight: 'Consistent quality and collaboration',
		role: 'Software Developer',
	},
	{
		id: 4,
		name: 'Abhinav M.',
		initials: 'AM',
		rating: 5.0,
		date: 'Oct 12, 2023',
		project: 'Build a responsive modern landing page',
		testimonial:
			"It's always a pleasure to work with Brian. He delivered a sleek and user-friendly landing page within the deadline, showcasing his professionalism and dedication. Brian's dedication and attention to detail truly shine through in his work. Looking forward to our future collaborations!",
		highlight: 'Professional dedication and attention to detail',
		role: 'Frontend Developer',
	},
	{
		id: 5,
		name: 'Abhinav M.',
		initials: 'AM',
		rating: 5.0,
		date: 'Jul 19, 2023',
		project: 'Convert Figma Design to Functional Web App',
		testimonial:
			'It was our pleasure to again work with Brian. Throughout the entire front-end design process for the LoftLime website, Brian exhibited a remarkable level of diligence, coordination, and attention to detail. Not only did Brian deliver outstanding design work, but his meticulous testing and quality assurance efforts also ensured a flawless user experience. His commitment to delivering a high-quality product was evident in every aspect of his work. It was a pleasure collaborating with Brian, and I... more',
		highlight: 'Meticulous testing and QA expertise',
		role: 'Software Developer',
	},
	{
		id: 7,
		name: 'Abhinav M.',
		initials: 'AM',
		rating: 5.0,
		date: 'Apr 22, 2023',
		project: 'Build a responsive modern app landing page',
		testimonial:
			'Brian is just more than awesome. He completed the task as expected on time with the good quality delivered. Would love to work again in the future!',
		highlight: 'Timely delivery with excellent quality',
		role: 'Frontend Developer',
	},
];
